@startuml
entity Competittion{
    stage
    group
    bout
    date
    address
    team_a
    team_a_score
    team_b
    team_b_score
    referee
}

entity Player{
    RankingTypeID
    PointsTot_ForAllPlayerStats
    SpikePerf
    SpikePos
    RecPos
    RecPerf
    PointsW_P
    Libero
    SpikeTot
    RecTot
    PlayedMatches
    PlayedSet
    SpikeWin_MatchWin
    SpikeWin_MatchLose
    BlockWin_MatchWin
    BlockWin_MatchLose
    ServeWin_MatchWin
    ServeWin_MatchLose
    RecEffPerc
    RecWinPerc
    ServeWinMatch
    ServeWinSet
    BlockWinSet
    SpikerEff
    SpikerPos
    SpikerPerSet
    PointsTot
    MatchName
    PointsPerMatch
    PointsPerSet
    PlayerSetData
    PlayerMatchID
    ChampionshipMatchID
    ChampionshipID
    TeamID
    PlayerID
    PlayedSets
    Points
    SideOut
    ServeErr
    ServeWin
    ServeMinus
    ServePlus
    ServeHP
    ServeEx
    RecErr
    RecWin
    RecMinus
    RecPlus
    RecHP
    RecEx
    SpikeErr
    SpikeWin
    SpikeMinus
    SpikePlus
    SpikeHP
    SpikeEx
    BlockErr
    BlockWin
    BlockMinus
    BlockPlus
    BlockHP
    BlockEx
    PositionID
    Captain
    Number
    Vote
    Surname
    Name
    Team
}

@enduml